# Generated by Django 5.0.6 on 2024-05-26 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_full', models.CharField(max_length=100)),
                ('state_abbr', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password_hash', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('zip', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmersMarkets.city')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmersMarkets.state')),
            ],
        ),
        migrations.CreateModel(
            name='MarketsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmersMarkets.category')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmersMarkets.market')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmersMarkets.state'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField()),
                ('score', models.IntegerField()),
                ('review', models.TextField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmersMarkets.market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmersMarkets.user')),
            ],
        ),
    ]
